markdown_extensions:
  - attr_list
  - meta
  - toc:
      permalink: true
  - pymdownx.mark
  - pymdownx.snippets:
      base_path: ["docs/snippets"]
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/custom.css

theme:
  name: material
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
    primary: white
    accent: light blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - navigation.footer
    - toc.integrate

site_name: Krux - Open-source signing device firmware for Bitcoin
site_description: Krux is open-source firmware that enables anyone to build their own Bitcoin signing device via off-the-shelf parts.
site_url: https://selfcustody.github.io/krux/
repo_url: https://github.com/selfcustody/krux
edit_uri: edit/main/docs
docs_dir: docs
site_dir: public
extra:
  social:
    - icon: fontawesome/solid/bullhorn
      link: https://bitcointalk.org/index.php?topic=5489022.0
      name: Send a message to the Bitcoin Forum
    - icon: fontawesome/brands/telegram
      link: https://t.me/SC_Krux
      name: Join our community-led Telegram
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/selfcustodykrux
      name: Follow us on X (Twitter)
    - icon: fontawesome/brands/github
      link: https://github.com/selfcustody/krux
      name: Our code on Github
  generator: true
copyright: 
  Powered by <a href="https://embit.rocks/">embit</a>, the Bitcoin library for Python 3 and Micropython

nav:
  - Home: index.en.md
  - Getting Started:
    - Getting Started: getting-started/index.en.md
    - Installing:
      - Installing: getting-started/installing/index.en.md
      - From GUI application: getting-started/installing/from-gui.en.md
      - From pre-built official release: getting-started/installing/from-pre-built-release.en.md
      - From pre-built test release: getting-started/installing/from-test-release.en.md
      - From source: getting-started/installing/from-source.en.md
    - Basic Usage:
      - Generating a Mnemonic: getting-started/usage/generating-a-mnemonic.en.md
      - Loading a Mnemonic: getting-started/usage/loading-a-mnemonic.en.md
      - Navigating the Main Menu: getting-started/usage/navigating-the-main-menu.en.md
      - Using a Single-sig Wallet: getting-started/usage/using-a-single-sig-wallet.en.md
      - Using a Multisig Wallet: getting-started/usage/using-a-multisig-wallet.en.md
    - Features:
      - Encrypted Mnemonics: getting-started/features/encrypted-mnemonics.en.md
      - Printing: getting-started/features/printing.en.md
      - SD Card Updates: getting-started/features/sd-card-update.en.md
      - Tools: getting-started/features/tools.en.md
      - Transcribing QR Codes: getting-started/features/QR-transcript-tools.en.md
    - Settings: getting-started/settings.en.md
    - Navigation Overview: getting-started/navigation.en.md
  - Devices and Parts List: parts.en.md
  - FAQ: faq.en.md
  - Support the Project: support.en.md

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
